apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ci-cd-demo
  description: My first Backstage demo service

  annotations:
    github.com/project-slug: harshhudda/ci-cd-demo

  links:
    - title: GitHub
      url: https://github.com/harshhudda/ci-cd-demo

spec:
  type: service
  lifecycle: experimental
  owner: user:guest
